# Generated by Django 4.2.21 on 2026-08-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_backfill_case_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=8),
        ),
    ]
