# Generated by Django 4.2.21 on 2026-07-30 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_created_by_caseshare'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('admin', 'Hành động quản trị'), ('auth', 'Xác thực'), ('business', 'Nghiệp vụ'), ('error', 'Lỗi hệ thống')], max_length=16)),
                ('action', models.CharField(choices=[('user_create', 'Tạo người dùng'), ('user_update', 'Cập nhật người dùng'), ('user_role_change', 'Đổi vai trò'), ('user_lock', 'Khoá tài khoản'), ('user_unlock', 'Mở khoá tài khoản'), ('user_delete', 'Xoá người dùng'), ('user_restore', 'Khôi phục người dùng'), ('settings_update', 'Cập nhật cài đặt'), ('login_success', 'Đăng nhập thành công'), ('login_failed', 'Đăng nhập thất bại'), ('logout', 'Đăng xuất'), ('session_timeout', 'Hết phiên do không hoạt động'), ('register', 'Đăng ký'), ('otp_verified', 'Xác thực OTP'), ('password_change', 'Đổi mật khẩu'), ('case_create', 'Tạo ca chẩn đoán'), ('case_done', 'Ca chẩn đoán hoàn thành'), ('case_failed', 'Ca chẩn đoán thất bại'), ('labels_edited', 'Bác sĩ sửa nhãn'), ('case_export', 'Tải kết quả'), ('case_share', 'Chia sẻ ca'), ('case_unshare', 'Thu hồi chia sẻ'), ('task_error', 'Lỗi tác vụ nền'), ('pipeline_error', 'Lỗi pipeline AI'), ('email_error', 'Lỗi gửi email')], max_length=32)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('target_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cases.case')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='users_activ_categor_9fd691_idx'), models.Index(fields=['action', '-created_at'], name='users_activ_action_2937b9_idx')],
            },
        ),
    ]
