# Generated by Django 4.2.21 on 2026-07-31 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_deleted_at_user_is_deleted_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('user_create', 'Tạo người dùng'), ('user_update', 'Cập nhật người dùng'), ('user_role_change', 'Đổi vai trò'), ('user_lock', 'Khoá tài khoản'), ('user_unlock', 'Mở khoá tài khoản'), ('user_delete', 'Xoá người dùng'), ('user_restore', 'Khôi phục người dùng'), ('settings_update', 'Cập nhật cài đặt'), ('role_request_approved', 'Duyệt yêu cầu vai trò'), ('role_request_rejected', 'Từ chối yêu cầu vai trò'), ('login_success', 'Đăng nhập thành công'), ('login_failed', 'Đăng nhập thất bại'), ('logout', 'Đăng xuất'), ('session_timeout', 'Hết phiên do không hoạt động'), ('register', 'Đăng ký'), ('otp_verified', 'Xác thực OTP'), ('password_change', 'Đổi mật khẩu'), ('case_create', 'Tạo ca chẩn đoán'), ('case_done', 'Ca chẩn đoán hoàn thành'), ('case_failed', 'Ca chẩn đoán thất bại'), ('labels_edited', 'Bác sĩ sửa nhãn'), ('case_export', 'Tải kết quả'), ('case_share', 'Chia sẻ ca'), ('case_unshare', 'Thu hồi chia sẻ'), ('task_error', 'Lỗi tác vụ nền'), ('pipeline_error', 'Lỗi pipeline AI'), ('email_error', 'Lỗi gửi email')], max_length=32),
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Bác sĩ nha khoa'), ('patient', 'Bệnh nhân')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=10)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='users_roler_status_b4a808_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rolerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='uniq_pending_role_request_per_user'),
        ),
    ]
