# Generated by Django 4.2.21 on 2026-08-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
        ('users', '0003_alter_activitylog_action_rolerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='module',
            field=models.CharField(choices=[('gingivitis', 'Viêm lợi · 2D'), ('canine3d', 'Răng nanh ngầm · 3D'), ('system', 'Hệ thống')], default='system', max_length=16),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scans.scan'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('user_create', 'Tạo người dùng'), ('user_update', 'Cập nhật người dùng'), ('user_role_change', 'Đổi vai trò'), ('user_lock', 'Khoá tài khoản'), ('user_unlock', 'Mở khoá tài khoản'), ('user_delete', 'Xoá người dùng'), ('user_restore', 'Khôi phục người dùng'), ('settings_update', 'Cập nhật cài đặt'), ('role_request_approved', 'Duyệt yêu cầu vai trò'), ('role_request_rejected', 'Từ chối yêu cầu vai trò'), ('login_success', 'Đăng nhập thành công'), ('login_failed', 'Đăng nhập thất bại'), ('logout', 'Đăng xuất'), ('session_timeout', 'Hết phiên do không hoạt động'), ('register', 'Đăng ký'), ('otp_verified', 'Xác thực OTP'), ('password_change', 'Đổi mật khẩu'), ('case_create', 'Tạo ca chẩn đoán'), ('case_done', 'Ca chẩn đoán hoàn thành'), ('case_failed', 'Ca chẩn đoán thất bại'), ('labels_edited', 'Bác sĩ sửa nhãn'), ('case_export', 'Tải kết quả'), ('case_share', 'Chia sẻ ca'), ('case_unshare', 'Thu hồi chia sẻ'), ('scan_upload', 'Tải phim CBCT lên'), ('scan_open_requested', 'Yêu cầu mở phim trong 3D Slicer'), ('scan_downloaded', 'Phim đã được tải về máy'), ('scan_delete', 'Xoá phim'), ('segmentation_upload', 'Nộp kết quả phân vùng'), ('task_error', 'Lỗi tác vụ nền'), ('pipeline_error', 'Lỗi pipeline AI'), ('email_error', 'Lỗi gửi email')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['module', '-created_at'], name='users_activ_module_d58c35_idx'),
        ),
    ]
