# Generated by Django 4.2.21 on 2026-08-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_backfill_activitylog_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('user_create', 'Tạo người dùng'), ('user_update', 'Cập nhật người dùng'), ('user_role_change', 'Đổi vai trò'), ('user_lock', 'Khoá tài khoản'), ('user_unlock', 'Mở khoá tài khoản'), ('user_delete', 'Xoá người dùng'), ('user_restore', 'Khôi phục người dùng'), ('settings_update', 'Cập nhật cài đặt'), ('role_request_approved', 'Duyệt yêu cầu vai trò'), ('role_request_rejected', 'Từ chối yêu cầu vai trò'), ('login_success', 'Đăng nhập thành công'), ('login_failed', 'Đăng nhập thất bại'), ('logout', 'Đăng xuất'), ('session_timeout', 'Hết phiên do không hoạt động'), ('register', 'Đăng ký'), ('otp_verified', 'Xác thực OTP'), ('password_change', 'Đổi mật khẩu'), ('case_create', 'Tạo ca chẩn đoán'), ('case_done', 'Ca chẩn đoán hoàn thành'), ('case_failed', 'Ca chẩn đoán thất bại'), ('labels_edited', 'Bác sĩ sửa nhãn'), ('case_export', 'Tải kết quả'), ('case_share', 'Chia sẻ ca'), ('case_unshare', 'Thu hồi chia sẻ'), ('scan_upload', 'Tải phim CBCT lên'), ('scan_open_requested', 'Yêu cầu mở phim trong 3D Slicer'), ('scan_downloaded', 'Phim đã được tải về máy'), ('scan_delete', 'Xoá phim'), ('segmentation_upload', 'Nộp kết quả phân vùng'), ('asset_upload', 'Tải dữ liệu lên kho'), ('asset_download', 'Tải dữ liệu từ kho'), ('asset_delete', 'Xoá dữ liệu khỏi kho'), ('task_error', 'Lỗi tác vụ nền'), ('pipeline_error', 'Lỗi pipeline AI'), ('email_error', 'Lỗi gửi email')], max_length=32),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(choices=[('gingivitis', 'Viêm lợi · 2D'), ('canine3d', 'Răng nanh ngầm · 3D'), ('library', 'Kho dữ liệu'), ('system', 'Hệ thống')], default='system', max_length=16),
        ),
    ]
