# Generated by Django 4.2.21 on 2026-09-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_activitylog_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("share", "Chia sẻ"), ("processing", "Xử lý dữ liệu"), ("role", "Vai trò"), ("system", "Hệ thống")], default="system", max_length=16)),
                ("level", models.CharField(choices=[("info", "Thông tin"), ("success", "Thành công"), ("warning", "Cảnh báo"), ("error", "Lỗi")], default="info", max_length=16)),
                ("title", models.CharField(max_length=160)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("link", models.CharField(blank=True, max_length=500)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["recipient", "read_at", "-created_at"], name="users_notif_rec_read_idx")],
            },
        ),
    ]
