# Generated by Django 4.2.21 on 2026-08-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='upload_chunk_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='upload_total_chunks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='upload_total_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
