# Generated by Django 4.2.21 on 2026-08-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scans", "0002_scan_upload_chunk_size_scan_upload_total_chunks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("permission", models.CharField(choices=[("view", "Chỉ xem"), ("edit", "Xem và nộp phân vùng")], default="view", max_length=8)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="scans.scan")),
                ("shared_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("shared_with", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shared_scans", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("scan", "shared_with")},
            },
        ),
    ]
