'use client';

import { useMemo, useState } from 'react';

type Status = 'pending' | 'confirmed' | 'waiting' | 'completed' | 'rejected';
type Appointment = { id: string; time: string; patient: string; phone: string; doctor: string; specialty: string; reason: string; status: Status; duration: number; note?: string };

const APPOINTMENTS: Appointment[] = [
  { id: 'TM-260914-01', time: '08:30', patient: 'Nguyễn Thu Hà', phone: '0903 215 684', doctor: 'BS. Nguyễn Minh Anh', specialty: 'Nha chu', reason: 'Tư vấn kết quả viêm lợi', status: 'completed', duration: 20 },
  { id: 'TM-260914-02', time: '10:00', patient: 'Trần Quốc Bảo', phone: '0918 440 129', doctor: 'BS. Trần Hoàng Nam', specialty: 'Chỉnh nha', reason: 'Giải thích phim CBCT răng nanh ngầm', status: 'pending', duration: 30 },
  { id: 'TM-260914-03', time: '13:30', patient: 'Lê Minh Khang', phone: '0971 662 843', doctor: 'BS. Nguyễn Minh Anh', specialty: 'Nha chu', reason: 'Tái tư vấn sau chăm sóc lợi', status: 'waiting', duration: 20 },
  { id: 'TM-260914-04', time: '15:00', patient: 'Phạm Gia Linh', phone: '0935 718 092', doctor: 'BS. Võ Thanh Tùng', specialty: 'Răng Hàm Mặt', reason: 'Tư vấn triệu chứng ê buốt răng', status: 'pending', duration: 25 },
  { id: 'TM-260914-05', time: '16:30', patient: 'Đỗ Anh Quân', phone: '0982 336 751', doctor: 'BS. Trần Hoàng Nam', specialty: 'Chỉnh nha', reason: 'Theo dõi kế hoạch chỉnh nha', status: 'confirmed', duration: 30 },
];

const labels: Record<Status, string> = { pending: 'Chờ duyệt', confirmed: 'Đã xác nhận', waiting: 'Chờ bệnh nhân', completed: 'Đã hoàn tất', rejected: 'Đã từ chối' };
const styles: Record<Status, string> = { pending: 'bg-violet-50 text-violet-700 border-violet-200', confirmed: 'bg-blue-50 text-blue-700 border-blue-200', waiting: 'bg-amber-50 text-amber-700 border-amber-200', completed: 'bg-green-50 text-green-700 border-green-200', rejected: 'bg-red-50 text-red-700 border-red-200' };

export default function ReceptionAppointmentsPage() {
  const [appointments, setAppointments] = useState(APPOINTMENTS);
  const [filter, setFilter] = useState<'all' | Status>('all');
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState<Appointment | null>(null);
  const [decision, setDecision] = useState<{ appointment: Appointment; status: 'confirmed' | 'rejected' } | null>(null);
  const [note, setNote] = useState('');
  const [notice, setNotice] = useState<string | null>(null);
  const items = useMemo(() => appointments.filter(item => (filter === 'all' || item.status === filter) && `${item.patient} ${item.doctor} ${item.reason}`.toLowerCase().includes(query.toLowerCase())), [appointments, filter, query]);

  function saveDecision() {
    if (!decision || (decision.status === 'rejected' && !note.trim())) return;
    setAppointments(rows => rows.map(row => row.id === decision.appointment.id ? { ...row, status: decision.status, note: note.trim() || undefined } : row));
    setNotice(decision.status === 'confirmed' ? `Đã duyệt và xác nhận lịch ${decision.appointment.id}.` : `Đã từ chối lịch ${decision.appointment.id}.`);
    setDecision(null); setSelected(null); setNote('');
  }

  return <div className="min-h-full w-full bg-slate-50 p-6 lg:p-8">
    <section className="flex justify-end">
      <button className="inline-flex items-center gap-2.5 rounded-2xl bg-primary px-6 py-4 text-base font-semibold text-white shadow-sm transition-colors hover:bg-primary-600"><span className="material-symbols-outlined text-[24px]">add</span>Thêm lịch hẹn</button>
    </section>
    {notice && <div className="mt-4 flex items-center justify-between rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800"><span>{notice}</span><button onClick={() => setNotice(null)}><span className="material-symbols-outlined text-[18px]">close</span></button></div>}

    <section className="mt-5 overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-gray-100 px-6 py-5"><div className="relative min-w-72 flex-1"><span className="material-symbols-outlined absolute left-4 top-1/2 -translate-y-1/2 text-[22px] text-gray-400">search</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Tìm bệnh nhân, bác sĩ hoặc nội dung tư vấn..." className="w-full rounded-xl border border-gray-200 py-3 pl-11 pr-4 text-base outline-none focus:border-primary" /></div><div className="flex rounded-xl bg-gray-100 p-1.5">{(['all', 'pending', 'confirmed', 'waiting', 'completed'] as const).map(item => <button key={item} onClick={() => setFilter(item)} className={`rounded-lg px-4 py-2 text-sm font-medium ${filter === item ? 'bg-white text-gray-900 shadow-sm' : 'text-gray-500'}`}>{item === 'all' ? 'Tất cả' : labels[item]}</button>)}</div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-base"><thead className="bg-gray-50 text-left text-xs font-semibold uppercase tracking-wide text-gray-500"><tr><th className="px-6 py-4">Thời gian</th><th className="px-6 py-4">Bệnh nhân</th><th className="px-6 py-4">Nội dung tư vấn</th><th className="px-6 py-4">Bác sĩ phụ trách</th><th className="px-6 py-4">Trạng thái</th><th className="px-6 py-4 text-right">Thao tác</th></tr></thead><tbody className="divide-y divide-gray-100">{items.map(item => <tr key={item.id} className="hover:bg-slate-50/70"><td className="px-6 py-5"><p className="text-lg font-semibold text-gray-900">{item.time}</p><p className="mt-1 text-sm text-gray-500">{item.duration} phút · Online</p></td><td className="px-6 py-5"><p className="text-lg font-medium text-gray-900">{item.patient}</p><p className="mt-1 text-sm text-gray-500">{item.phone}</p></td><td className="px-6 py-5"><p className="text-gray-800">{item.reason}</p><p className="mt-1 font-mono text-xs text-gray-400">{item.id}</p></td><td className="px-6 py-5"><p className="text-gray-800">{item.doctor}</p><p className="mt-1 text-sm text-gray-500">{item.specialty}</p></td><td className="px-6 py-5"><span className={`inline-flex rounded-full border px-3 py-1.5 text-sm font-medium ${styles[item.status]}`}>{labels[item.status]}</span></td><td className="px-6 py-5 text-right"><div className="flex justify-end gap-2">{item.status === 'pending' && <><button onClick={() => setDecision({ appointment: item, status: 'confirmed' })} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-medium text-white">Duyệt</button><button onClick={() => setDecision({ appointment: item, status: 'rejected' })} className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-medium text-red-700">Từ chối</button></>}<button onClick={() => setSelected(item)} className="rounded-xl border border-primary/20 px-4 py-2.5 text-sm font-medium text-primary hover:bg-primary-50">Chi tiết</button></div></td></tr>)}</tbody></table></div>
      {items.length === 0 && <p className="p-10 text-center text-sm text-gray-400">Không có lịch hẹn phù hợp.</p>}
    </section>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={() => setSelected(null)}><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl" onClick={e => e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-primary">{selected.id} · Dữ liệu demo</p><h3 className="mt-1 font-serif text-lg font-semibold text-gray-900">Lịch tư vấn {selected.time}</h3></div><button onClick={() => setSelected(null)} className="text-gray-400"><span className="material-symbols-outlined">close</span></button></div><dl className="mt-5 space-y-3 text-sm"><div><dt className="text-xs text-gray-500">Bệnh nhân</dt><dd className="mt-0.5 font-medium">{selected.patient} · {selected.phone}</dd></div><div><dt className="text-xs text-gray-500">Bác sĩ phụ trách</dt><dd className="mt-0.5">{selected.doctor} · {selected.specialty}</dd></div><div><dt className="text-xs text-gray-500">Nội dung</dt><dd className="mt-0.5">{selected.reason}</dd></div></dl><div className="mt-6 flex justify-end gap-2">{selected.status === 'pending' && <><button onClick={() => setDecision({ appointment: selected, status: 'rejected' })} className="rounded-xl border border-red-200 px-4 py-2 text-sm text-red-700">Từ chối</button><button onClick={() => setDecision({ appointment: selected, status: 'confirmed' })} className="rounded-xl bg-primary px-4 py-2 text-sm font-medium text-white">Duyệt lịch</button></>}<button onClick={() => setSelected(null)} className="rounded-xl border border-gray-200 px-4 py-2 text-sm">Đóng</button></div></div></div>}
    {decision && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 p-4" onClick={() => setDecision(null)}><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl" onClick={e => e.stopPropagation()}><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${decision.status === 'rejected' ? 'bg-red-50 text-red-600' : 'bg-primary-50 text-primary'}`}><span className="material-symbols-outlined">{decision.status === 'rejected' ? 'event_busy' : 'event_available'}</span></span><h3 className="mt-4 font-serif text-lg font-semibold text-gray-900">{decision.status === 'rejected' ? 'Từ chối lịch hẹn' : 'Duyệt lịch hẹn'}</h3><p className="mt-1 text-sm text-gray-500">{decision.status === 'rejected' ? `Nhập lý do để phản hồi ${decision.appointment.patient}.` : `Xác nhận lịch ${decision.appointment.time} với ${decision.appointment.doctor}.`}</p><textarea value={note} onChange={e => setNote(e.target.value)} placeholder={decision.status === 'rejected' ? 'Lý do từ chối (bắt buộc)' : 'Ghi chú nội bộ (không bắt buộc)'} className="mt-4 min-h-24 w-full rounded-xl border border-gray-200 p-3 text-sm outline-none focus:border-primary" /><div className="mt-5 flex justify-end gap-2"><button onClick={() => { setDecision(null); setNote(''); }} className="rounded-xl border border-gray-200 px-4 py-2 text-sm">Huỷ</button><button onClick={saveDecision} disabled={decision.status === 'rejected' && !note.trim()} className={`rounded-xl px-4 py-2 text-sm font-medium text-white disabled:opacity-50 ${decision.status === 'rejected' ? 'bg-red-600' : 'bg-primary'}`}>{decision.status === 'rejected' ? 'Xác nhận từ chối' : 'Duyệt và thông báo'}</button></div></div></div>}
  </div>;
}
